---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

# Configure MySQL.
- import_tasks: configure.yml
- import_tasks: secure-installation.yml
- import_tasks: databases.yml
- import_tasks: users.yml
- import_tasks: replication.yml

- include_tasks: encrypt-at-rest.yml
  when: mysql_encrypt_at_rest | bool
  tags:
  - 'role::mysql'
  - 'role::mysql::config'
  - 'role::mysql::encrypt'

- include_tasks: secure-tls-cfg.yml
  when: mysql_tls_setup | bool
  tags:
    - 'role::mysql'
    - 'role::mysql::config'
    - 'role::mysql::tls'
